### ISSUE TITLE
Is it reliable to transfer coins from exchange A to exchange B?

### ISSUE THREAD

**Issue by L7788** [aeonix/aeon#101]
When transferring coins from exchange A to exchange B, if exchange A allows to input exchange B's payment id and base address, is this transfer reliable? If so, then I don't need to transfer exchange A > my local pc wallet -> exchange B any more.

**Comment by sammy007** [comment]
Are you sure this is appropriate place for your question?

**Comment by L7788** [comment]
I assume it is. Because it is more like to a technical design related. Isn't it? If not, I can remove this. Please advise.

**Comment by sammy007** [comment]
You made incorrect assumption.

**Comment by L7788** [comment]
Sorry, I delete it. I apologize.
