### ISSUE TITLE
Release name for v0.13.0 hard fork

### ISSUE THREAD

**Issue by stoffu** [aeonix/aeon#124]
Please propose a release name for the next v0.13.0 hard fork.
From the discussion thread for the previous fork #6:

> Two possible naming conventions were proposed:
> - pick names of Greek deities (https://en.wikipedia.org/wiki/List_of_Greek_mythological_figures)
> - pick names related to Gnosticism (https://en.wikipedia.org/wiki/Aeon_(Gnosticism))

My vote: _Aletheia_ (from Gnosticism, meaning truth)

**Comment by BigslimVdub** [comment]
I think either Aletheia, Archon (Aeon Creator), or Ainos (Ever lasting) are good candidates.

**Comment by 420coupe** [comment]
+1 Aletheia

**Comment by jwinterm** [comment]
Aletheia sounds pretty cool, maybe hard to pronounce. Atlas could be good one for foundational change that will provide support for the network (hopefully).
