### ISSUE TITLE
Integrate monero pr 5165 to allow electron wallet restore function

### ISSUE THREAD

**Issue by BigslimVdub** [aeonix/aeon#127]
Currently the ported electron wallet will. It restore wallet files or import due to lack of rpc function. Can we add this to have a fully functioning electron wallet: 
https://github.com/monero-project/monero/pull/5165

Also import wallet function rpc would be helpful as well.

**Comment by stoffu** [comment]
#128

**Comment by BigslimVdub** [comment]
Closing as #128 now merged.
