### ISSUE TITLE
Out of memory while compiling on a Debian computer

### ISSUE THREAD

**Issue by Carnat89** [aeonix/aeon#153]
Hello, 

I have an issu when i try to compile the project "instruction "make" : 

 fir aeon/contrib/epee/src/http_auth.cpp 

out of memory the process cc1plus is killed. 

Any idea ?

**Comment by stoffu** [comment]
Probably you need to increase the swap size, but no idea as I don't use Debian. Maybe compile Monero to reproduce the same issue, and open an issue in the Monero repository. You have a higher chance of getting a solution which should also apply to building Aeon.

**Comment by iamsmooth** [comment]
Yeah I'm pretty sure that is just not having enough memory/swap for the compile process and not an issue with AEON (or, most likely, Monero). I'll be closing this.
