### ISSUE TITLE
Download .raw blockchain file for AEON

### ISSUE THREAD

**Issue by lluke777** [aeonix/aeon#158]
Is it possible to download raw blockchain for AEON  instead of syncing from scratch? 
I am looking similar link to monero like:
https://downloads.getmonero.org/blockchain.raw

**Comment by stoffu** [comment]
It is possible, but is most likely slower than simply syncing via P2P.

No such link exists in AEON website.

**Comment by BigslimVdub** [comment]
Some pool ops may provide a .raw download link for you but I also agree sync from 0 will only take 45min on modern hardware and a decent internet connection.

**Comment by ghost** [comment]
I would say this is resolved now and can be closed seeing the downloads page. https://www.aeon.cash/en/downloads/
