### ISSUE TITLE
Warning-as-Error Stops Build

### ISSUE THREAD

**Issue by marmulak** [aeonix/aeon#173]
OS: Fedora 31 x86_64
gcc version 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC)

When attempting to build Aeon I get the following error:

>/crypto/git/aeon/src/wallet/wallet2.cpp: In member function ‘void tools::wallet2::refresh(bool, uint64_t, uint64_t&, bool&)’:
>/crypto/git/aeon/src/wallet/wallet2.cpp:2563:8: error: variable ‘refreshed’ set but not used [-Werror=unused-but-set-variable]
> 2563 |   bool refreshed = false;
>      |        ^~~~~~~~~
>cc1plus: all warnings being treated as errors
>make[3]: *** [src/wallet/CMakeFiles/obj_wallet.dir/build.make:63: src/wallet/CMakeFiles/obj_wallet.dir/wallet2.cpp.o] Error

I was able to avoid this error and build successfully by commenting out the following lines (575-577) from CMakeLists.txt:

>  if(NOT MINGW)
>    set(WARNINGS_AS_ERRORS_FLAG "-Werror")
>  endif()

No -Werror, no build error.

I checked Monero for anything resembling this and noted that its CMakeLists.txt nowhere contains -Werror

I leave it to you to decide the best way to resolve this.

**Comment by iamsmooth** [comment]
Fixed by #170
