### ISSUE TITLE
Name for v0.14.0 release (hard fork v9)

### ISSUE THREAD

**Issue by stoffu** [aeonix/aeon#195]
As the next hard fork seems to be nearing with #194, we need to come up with the name for the next software release.

Copying from the last discussion #124:

>    Two possible naming conventions were proposed:
>
>        pick names of Greek deities (https://en.wikipedia.org/wiki/List_of_Greek_mythological_figures)
>        pick names related to Gnosticism (https://en.wikipedia.org/wiki/Aeon_(Gnosticism))

This time I haven't come up with my choice yet.
Please feel free to propose one.

**Comment by BigslimVdub** [comment]
Cronos - God of time

Makes sense because of difficulty adjustment for longer block times if HF reasoning

**Comment by stoffu** [comment]
@BigslimVdub 
I like your idea, but the Wikipedia page https://en.wikipedia.org/wiki/List_of_Greek_mythological_figures#Primordial_deities says:

> Ancient Greek name: Χρόνος (Khrónos)
> English name: Chronos
> Description: The god of empirical time, sometimes equated with Aion. Not to be confused with the Titan Cronus (Kronos), the father of Zeus.

Isn't Chronos the correct one?

**Comment by BigslimVdub** [comment]
Yes Chronos, spelling error

**Comment by stoffu** [comment]
#197

**Comment by iamsmooth** [comment]
Release has been tagged
