### ISSUE TITLE
aeon-wallet-cli fails to convert old wallet

### ISSUE THREAD

**Issue by cryptonote-social** [aeonix/aeon#20]
I copied my wallet files over from my old repository and tried to open them with the new sophia-version of aeon-wallet-cli, and I get:

> Error: failed to load wallet: unsupported version

..and then the client exits.

I understand from others that it's supposed to be able to convert the wallet over?

I ended up restoring the wallet from seed, which worked but took a long time.

**Comment by shigutso** [comment]
you have to restore your old wallet with the mnemonic seed

just restore it with a predefined height and you'll be fine

for example, my pool started in January of this year, so I just resynced my pool wallet from height 900,000 and it tooks 2 minutes to finish syncing

**Comment by stoffu** [comment]
That release note may be a bit misleading (I'll ask smooth to reword it). The new CLI can read the same .keys which contains the wallet keys, but it can't read/convert the old wallet cache file (the file without any file extension), so it'll create the wallet cache from scratch by scanning the blockchain again.

By the way, I'm curious as to how the reported error message "Error: failed to load wallet: unsupported version" would be caused. Can you run the CLI with `--log-level 4` and post the log? The log won't include any critical private data such as wallet keys.

**Comment by cryptonote-social** [comment]
Didn't offer anything else:

> ./aeon-wallet-cli --log-level 4
This is the command line Aeon wallet. It needs to connect to a Aeon
daemon to work correctly.
WARNING: Do not reuse your Aeon keys on an another fork, UNLESS this fork has key reuse mitigations built in. Doing so will harm your privacy.

Aeon 'Sophia' (v0.12.0.0-master-release)
Logging to ./aeon-wallet-cli.log
Specify wallet file name (e.g., MyWallet). If the wallet doesn't exist, it will be created.
Wallet file name (or Ctrl-C to quit): xxx-wallet
Wallet and key files found, loading...
Wallet password: xxxx
Error: failed to load wallet: unsupported version

**Comment by stoffu** [comment]
Thanks for sharing the log, now I see how the error message is caused (it couldn't read the old wallet cache file). 

You can avoid this error by deleting the wallet cache file.

**Comment by stoffu** [comment]
The process of deleting/moving the old wallet cache file is manual, and I think it’s OK as it’s just a one-time operation.

**Comment by stoffu** [comment]
Actually I'm not able to reproduce the error you reported. What OS are you using? Are you using the official release binary, or did you build the code yourself? If the latter is the case, what build configuration did you use?

**Comment by cryptonote-social** [comment]
Ubuntu 16.04 LTS, built from source .... I think I just built it with:

cmake .. -DBUILD_SHARED_LIBS=1
make

(dynamic linking since I use the hashing libs for my pool)

let me know if you'd like me to try a static link or anything else.

**Comment by stoffu** [comment]
I still can't reproduce the error. I'm pretty sure it's related to the stack trace feature, but I'm not very familiar with it and I don't know why I don't get the same error as yours even when the feature is enabled (CMake prints `Stack trace on exception enabled (using easylogging++)`).

Can you try building it with this CMake option `-DSTACK_TRACE=OFF`?

**Comment by cryptonote-social** [comment]
Done. Same error message. Log file attached.
[aeon-wallet-cli.log](https://github.com/aeonix/aeon/files/2060637/aeon-wallet-cli.log)

**Comment by stoffu** [comment]
Now I understood what was happening and how to reproduce the error. Anyway, this problem is due to the old wallet cache file being incompatible with the new format, which is going to be less and less of a concern as the user base grows. We also explicitly advise users to delete/move the old wallet cache file when migrating to the new software. As such, I'm not going to add support for this legacy file compatibility issue.
