### ISSUE TITLE
The windows build error is due to MinGW using Boost 1.74 which has some flaws: https://github.com/boostorg/serialization/issues/219

### ISSUE THREAD

**Issue by ghost** [aeonix/aeon#204]
The windows build error is due to MinGW using Boost 1.74 which has some flaws: https://github.com/boostorg/serialization/issues/219

_Originally posted by @stoffu in https://github.com/aeonix/aeon/issues/201#issuecomment-713241992_

**Comment by iamsmooth** [comment]
There's a macOS build issue too

**Comment by ghost** [comment]
I see that now. It is posted in the logs: `error: no type named 'library_version_type' in namespace 'boost::serialization'; did you mean 'item_version_type'? 316 const boost::serialization::library_version_type library_version(` I did a quick google and found the moneromoo commit: https://github.com/monero-project/monero/commit/07442a60593a662161139947f6fbf29265fc8a5f
Here is a stackexchange thread related to the error from a monero contributor: https://stackoverflow.com/questions/65179639/monero-bigsur-update-no-member-named-library-version-type-in-namespace-boos

**Comment by ghost** [comment]
mac os solved by #207

**Comment by ghost** [comment]
windows #212
