### ISSUE TITLE
try a listing request in Kraken

### ISSUE THREAD

**Issue by ghost** [aeonix/aeon#208]
This, has to be done by the developers, this is why i'm posting this here.
https://support.kraken.com/hc/en-us/articles/360001388206-New-coin-listing-requests

The reasoning, is that Bittrex, will most likely delist aeon soon.
So if Kraken list it, there's high probability they will inherit the trading volume.
This increases the probability they will accept.

Also, Kraken didn't bother delisting ripple (for now?). In general, they aren't ubber paranoid like Bittrex. So there's a reasonable probability that they will accept. Make sure to tell them in the official listing request, that they will inherit the trading volume from Bittrex. This should make the request stand out from the crowed.

**Comment by ghost** [comment]
Not against it, but I'm sure they know this coin and they say:
`We have a team that researches cryptocurrency projects and if a project catches our interest and meets our checklist of requirements, we'll reach out to the project developers.`
`Emailing us does not increase the chances of listing with us in any way.` 
I don't know if there is much that can be accomplished on this front except continuing to make Aeon better.

**Comment by ghost** [comment]
I also found this on kraken blog

WARNING: Bitcoin SV does NOT meet Kraken’s usual listing requirements. It should be seen as an extremely high risk investment. There are many red flags that traders should be aware of:

- No known wallets supporting replay protection (be careful!)
- No support in major block explorers
- Miners apparently subsidized or operating at a loss
- Representatives threatening and openly hostile toward other chains
- Chain’s survival may be mutually exclusive with other chains
- Supply is temporarily constrained because of limited wallet support
- Some large holders have indicated they’d be dumping everything ASAP
- Kraken has done only very minimal code review

https://blog.kraken.com/post/1928/kraken-credits-clients-with-bitcoin-sv-bsv-and-launches-bsv-trading/

**Comment by BigslimVdub** [comment]
FYI I submitted a listing request Circa 12-2019 with the response of a generic thanks for submitting we will present to the developers your coin. 

I responded back a few months later with the response of the project is in queue for review. 

It appears Aeon is not of interest at least during that time for listing. As of today, bittrex has not announced delisting of aeon.

**Comment by ghost** [comment]
for those that don't know
Bittrex delisted Monero, Dash, Zcash and Grin
https://twitter.com/BittrexGlobal/status/1345056051310325761

all are privacy, or perceived privacy coins. Grin was added in  the list later.
To my knowledge only  aeon and haven remain.

**Comment by ghost** [comment]
I believe we should make a push for exchange listings after finishing logo update and website fixes. maybe in a month or two.

**Comment by ghost** [comment]
Collecting a list of potential exchanges would be a good start

**Comment by BigslimVdub** [comment]
Sorry I totally forgot about this. I’ll see if I can get some things together for it. Also recheck poloneix and maybe others. It seems many exchanges have added monero the last year or so that never had CN coins before.

**Comment by ghost** [comment]
No worries, I am not in a rush for this right now either. It would be good to collect some information first such as: what exchanges, why a listing aeon is a good idea, what has aeon community accomplished since the last listing request, etc. Then we make a real true case for aeon to give to exchanges for getting listed.  I am too focused on website and other things to look at this right now but I definitely want to make a big push once things have been settled on community websites and logo.

**Comment by ghost** [comment]
Kraken likely knows of Aeon already. Either they are waiting for the right time, or they are simply not interested. So I guess time will tell.

**Comment by ghost** [comment]
this should be reconsidered again, given that bittrex is delisting aeon.

in short:
1. devs must do the request (kraken policy)
2. kraken is adding coins all the time
3. bittrex is delisting privacy coins in general, even monero, that's the reason for the delisting
4. kraken, will inherit the trade volume from bittrex
5. aeon is not a scam

**Comment by iamsmooth** [comment]
> devs must do the request (kraken policy)

I don't know what is meant by "devs". It wouldn't make sense for people whose primary contribution is as a coder to do this for example. We do not have any sort of company or foundation or anything else that would constitute an "official" agent of the project.

This is an open community project. Go ahead and volunteer yourself as the "official" "Exchange listing coordinator". (This is directed to any community member, not exclusively you specifically.) Make it so.

**Comment by BigslimVdub** [comment]
> > devs must do the request (kraken policy)
> 
> I don't know what is meant by "devs". It wouldn't make sense for people whose primary contribution is as a coder to do this for example. We do not have any sort of company or foundation or anything else that would constitute an "official" agent of the project.
> 
> This is an open community project. Go ahead and volunteer yourself as the "official" "Exchange listing coordinator". (This is directed to any community member, not exclusively you specifically.) Make it so.

Exchanges require correspondence from the official domain of the project or members considered dev team (contributors to the project codebase) when submitting listing requests. Without this, the listing requests are ignored or declined.

**Comment by iamsmooth** [comment]
Well, we can't even send email "from AEON" as far as I know.

If they want someone to be listed as a contact on the web site, we can do that. In fact, you know how to do that: PR to the web repo.

**Comment by ghost** [comment]
the proverbial kernel developer trying to design a gui.... -_-

Some one officially from the project needs to contact them. I suspect it's not just to filter the requests. Above about Bitcoin SV, it mentions that "Kraken has done only very minimal code review". So i'm assuming it will get technical.

My main sales pitch, is that they will inherit the trade volume from bittrex( easy money) and bittrex is ejecting all privacy coins, including monero( aeon is not a scam).
