### ISSUE TITLE
Request to Smooth for proof of dev fund. 

### ISSUE THREAD

**Issue by ghost** [aeonix/aeon#215]
I would like to make a **request** that Smooth provide proof of dev funds. 
This funds has never been confirmed to exist because we are limited to the view wallet perspective.

They, @iamsmooth, can accomplish this by locking the funds in a tx for a small number of blocks.
When all of the funds have been locked **simultaneously**, 
the tx keys can be shared publicly under get_tx_proof
Then the sum can be formed to calculate the amount in the dev fund wallet.

I believe this can be a good show of transparency.

**Comment by BigslimVdub** [comment]
There have been many requests for this in the past 5 years and all have ended in the same result. To clear the matter and bring legitimacy to the project and smooth long term there should be absolute clarity on the concern however even if there are coins it really doesn’t matter because whoever owns the keys owns the coins. If @iamsmooth owns the keys he owns the coins if there are any left. 

Personal wallet != “dev fund wallet”. I think a lot of people misconstrue the difference between those. 

The community funding wallet solved this issue on https://www.aeonfunding.com allowing all viewers to know the current balance so long as the site is not down.

**Comment by ghost** [comment]
So Big Slim are you in support of this request?

**Comment by ghost** [comment]
I believe smooth would save the coins to be used for AEON and not their self. Given an opportunity to prove it, and enough community support, I think they would gladly agree to show proof of funds as i described in the first post. Largely smooth is very encouraging towards the project.

**Comment by iamsmooth** [comment]
This is a good idea, and I will see that it happens ASAP. It will be a little tedious to implement because the donations are in a very large number of mostly small outputs, so it will need to be consolidated first.

The donations have mostly not been touched apart from a few (publicly stated) situations where they were used to pay bounties.

**Comment by iamsmooth** [comment]
BTW, there is also a BTC donation address which is transparent. The address is in the bitcointalk thread (maybe also on the web site?). It received one donation a while back which has not been touched (and has obviously gained value due to BTC price appreciation)

**Comment by ghost** [comment]
Thanks Smooth I am glad you have agreed. I will help to assemble some transparency report after the proofs are provided to document what has been distributed to where and how others can also audit the proofs themselves.

**Comment by BigslimVdub** [comment]
Smooth, I believe that prior donations and tx are negligent so long as today’s count can be verified for Aeon. Additional donations outside aeon would be nice if the count is more than a small amount (say a few hundred dollars worth).

**Comment by iamsmooth** [comment]
@BigslimVdub I didn't understand that comment.

**Comment by iamsmooth** [comment]
@yorha-0x If I'm not mistaken the tx proofs aren't even needed, since the view key for the donation address is public. If the coins are resent back to that address and locked, it can be seen that they arrived there (via view key) and unspent (since locked).

**Comment by BigslimVdub** [comment]
> @yorha-0x If I'm not mistaken the tx proofs aren't even needed, since the view key for the donation address is public. If the coins are resent back to that address and locked, it can be seen that they arrived there (via view key) and unspent (since locked).

This would probably be the easiest and quickest way to prove. 



> @BigslimVdub I didn't understand that comment.

Sorry, I was referring to not needing to show past donations only the current balance. I think simply sending the coins to your own wallet would allow visibility via pub view key as mentioned above however the block(s) would be interesting if indeed there are 750k coins since the tx would most likely have to be split to multiple tx

**Comment by iamsmooth** [comment]
I don't think there was ever 750k coins. My recollection was about 450k but I could be wrong. It's posted on bitcointalk, whatever it was (should be about the same now, unless someone made a large donation I'm not aware of).

**Comment by ghost** [comment]
I loaded up the wallet once. It was closer to smooths estimate. Also agreed on not needing tx proofs, that is simpler method to just use view key.

**Comment by BigslimVdub** [comment]
> I don't think there was ever 750k coins. My recollection was about 450k but I could be wrong. It's posted on bitcointalk, whatever it was (should be about the same now, unless someone made a large donation I'm not aware of).

Sorry I stand corrected however this was from 2017. Also note btc wallet 

https://www.reddit.com/r/Aeon/comments/7a8b2y/aeon_dev_funds/

**Comment by ghost** [comment]
Is this the only recorded use of dev funds? ~ 40 K
https://www.reddit.com/r/Aeon/comments/83iv5y/rebase_payouts_under_way/



Thanks for link Bigslim

AEON address: WmsSWgtT1JPg5e3cK41hKXSHVpKW7e47bjgiKmWZkYrhSS5LhRemNyqayaSBtAQ6517eo5PtH9wxHVmM78JDZSUu2W8PqRiNs
View Key: 71bf19a7348ede17fa487167710dac401ef1556851bfd36b76040facf051630b

BTC address:  12Cyjf3qV6qLyXdzpLSLPdRFPUVidvnzFM

**Comment by ghost** [comment]
Looks like there is BCH sitting there too from fork, .81

**Comment by iamsmooth** [comment]
@yorha-0x There were some smaller payouts for things like updating miners and pool code, maybe some other small dev tasks. They're buried in the bitcointalk thread somewhere. Mostly the original 400k+ which largely came from an anonymous donor early on as well as some months/years of mining by seed node servers (when CPU mining was efficient) paid for by me (plus various other donations from the community), is all still there.

**Comment by BigslimVdub** [comment]
> Looks like there is BCH sitting there too from fork, .81

Dont forget about bitcoinSV ;) https://blockchair.com/search?q=12Cyjf3qV6qLyXdzpLSLPdRFPUVidvnzFM

**Comment by ghost** [comment]
Oh yeaahh * Koolaid man *

**Comment by ghost** [comment]
@iamsmooth Ok great. Standing by.

**Comment by ghost** [comment]
Collected some tidbits from bitcoin talk suggesting 29000 in bounties


10000 AEON - pool software upgrade bounty
9000 AEON - GPU miner upgrade bounty
10000 AEON - Wolf0 miner and upgrade

```

July 16, 2015, 07:47:17 PM

Starting bids:

pool software: 10000 AEON

tsiv miner: 10000 AEON

I'm awarding the contract for the pool upgrade bounty to MoneroMooo for 10 000 AEON.

myagui and MoneroMooo are awarded the contract to upgrade the tsiv nvidia miner for 9500 AEON.


  ' Author',
  'Topic: [ANN] AEON: Scalable, private, mobile-friendly cryptocurrency \xa0'
  '(Read 619087 times)',
  '',
  'MoneroMooo',
  'Legendary',
  ' Offline',
  'Activity: 1280',
  'Merit: 1001',
  'Re: [ANN] AEON Gen 2 Cryptonote, Anon, Mobile-friendly, Scalable, New '
  'roadmap+Dev',
  'July 16, 2015, 01:57:48 PMLast edit: July 16, 2015, 03:11:52 PM by '
  'MoneroMooo',
  ' \xa0#1261',
  'Quote from: myagui on July 16, 2015, 01:44:17 PM@Moneromoo : Could I be '
  'awarded with the nvidia compilation / testing ? \xa0Sure Edit:QuoteEdit: '
  'For the joint effort with Moneromoo, I bid my portion of the task at 4500 '
  'AEON.Same. So a joint bid of 9000.',

Re: [ANN] AEON -- MANDATORY UPDATE, HARD FORK BLOCK 592000 (approx 2015-08-04)
July 22, 2015, 07:24:56 PM
	
Reply with quote  #1327
Quote from: dnaleor on July 22, 2015, 01:43:31 PM
The OTC topic had some nice volume, so it's time for a new donation. I'll donate 700 AEON, making my total donation 1000 AEON, now worth about 30 XMR Wink

Keep devving guys, you're doing a great job Smiley

Thank you for the donation!

The current donation balance is:

balance: 413537.378217015222, unlocked balance: 413537.378217015222

Spent:

10000 AEON - pool software upgrade bounty
9000 AEON - GPU miner upgrade bounty

19000 AEON - total



  ' \xa0#1327',
  'Quote from: dnaleor on July 22, 2015, 01:43:31 PMThe OTC topic had some '
  "nice volume, so it's time for a new donation. I'll donate 700 AEON, making "
  'my total donation 1000 AEON, now worth about 30 XMR Keep devving guys, '
  "you're doing a great job Thank you for the donation!The current donation "
  'balance is:balance: 413537.378217015222, unlocked balance: '
  '413537.378217015222Spent:10000 AEON - pool software upgrade bounty9000 AEON '
  '- GPU miner upgrade bounty19000 AEON - total',
  
  

Activity: 2618
Merit: 1167



View Profile Personal Message (Offline)
Trust: +9 / =0 / -0
Ignore
	
	
Re: [ANN] AEON 2nd gen cryptonote, anon, mobile-friendly, scalable, pruning
December 30, 2015, 05:37:00 AM
	
Reply with quote  #2508
The open source AMD GPU miner bounty of 9000 AEON has been paid out to Wolf0.

Here is our current donation fund balance (various small donations and mined blocks also received since the last report):

balance: 450158.232169665722, unlocked balance: 450125.527120220919


  'Merit: 1167',
  'Re: [ANN] AEON 2nd gen cryptonote, anon, mobile-friendly, scalable, pruning',
  'January 06, 2016, 07:01:34 AM',
  ' \xa0#2531',
  "Quote from: Wolf0 on January 06, 2016, 06:51:20 AMI'd like to remind people "
  '(AMD miners especially) that due to a mixup, 380 XMR is required to fund '
  'the miner proposal enough for the final performance milestone to be paid '
  "out - when it's funded, I can release the code which completes it. Details "
  'are here (see the comments for information on the mixup): '
  'https://forum.getmonero.org/9/work-in-progress/2400/open-source-amd-miner-by-wolf0The '
  "miner is rather close to Claymore's speeds on Tahiti (7950/7970/280/280X) "
  'and Hawaii (290/290X/295X2) - the latter may even be slightly faster, in '
  'the case of Elpida GDDR5. Current results of the code I have (as of yet '
  'unpublished) are here (nsfw): '
  'https://ottrbutt.com/miner/xmrwolf-12262015.pngWhy should you care? Unlike '
  'most miner optimizations - which cause mostly zero change to profits once '
  'everyone upgrades and difficulty adjusts - this miner will result in higher '
  "profits for miners overall, because it doesn't have the 2.5% Claymore fee. "
  'This means every miner mining with AMD gets more profit than they would '
  'have otherwise. The speed increases will also be pushed to the '
  'Cryptonight-lite version of the miner, allowing people to mine AEON and any '
  "other coin using that PoW with far better speeds - Claymore hasn't made a "
  'miner for these coins, so AMD miners were out of luck until mine was '
  'released.(copied from Monero ANN)The development/donation fund will '
  'contribute 1000 AEON in appreciation for pushing the updated CN-lite '
  'version. That is in addition to the 9000 already paid for the original '
  'development, which did not require improved versions.This will of course '
  'have to wait until the Monero community reaches the final milestone on that '
  'project. Some people here may wish to support that as well (see link above)',
  'btcluka',
```

**Comment by iamsmooth** [comment]
For reference here is the current balance

`Balance: 445400.615362308235, unlocked balance: 445400.615362308235`

Obviously that can't be verified by anyone at this point, but we'll get that addressed.

**Comment by iamsmooth** [comment]
For transparency I will be using this temporary wallet to consolidate the outputs currently in the donations wallet

Generated new wallet: Wmu4KRPNzEFe7CByDR8uMSMZKUWxLsYMcVcTSRQFb47gekxeqvFwZxDGyYvrj6zNbfP1tGCsPpMUzcVHHsraz8SK2VnNrM7mT
View key: 6c02ae98d149bb97b7cc5ee7cad7d317c370ad02d34db8f96ed3f1c29a57d003

**Comment by iamsmooth** [comment]
Transaction fab9d1e6731d7fc0dffc1bcfbb2f81448e87693606d7e2077a5b77fdca067c5a sent to the donations account locked for 5000 blocks (about two weeks) with a total of 445369.

There is a small amount missing due to various forms of breakage including a large amount of dust and unmixable outputs in the donations address as well as fees used for the consolidation process.

**Comment by ghost** [comment]
Ok that is great news. Every AEON holder can sleep well tonight.  

I went through to calculate I am missing about 32000. Any idea where they could be or how to explain? Were funds consolidated at some points?

|Date|Time|Reported Donation Fund|Reported Spent|Reported Received|Actual Received|Difference|Reference|
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |------------- |
|2015-04-30|21:58:33|5494.56612723058|0|5494.56612723058|5494.56612723058|0|https://bitcointalk.org/index.php?topic=641696.msg11244951#msg11244951|
|2015-07-22|12:51:34|413537.378217015|19000|432537.378217015|435063.506989389|2526.12877237325|https://bitcointalk.org/index.php?topic=641696.msg11945548#msg11945548|
|2015-09-06|10:48:33|439488.953356883|19000|458488.953356883|461679.330547446|3190.3771905629|https://bitcointalk.org/index.php?topic=641696.msg12346873#msg12346873|
|2015-12-30|23:22:13|450158.232169666|29000|479158.232169666|483231.460765723|4073.22859605734|https://bitcointalk.org/index.php?topic=641696.msg13396158#msg13396158|
|2016-08-30|11:39:13|461455.323546531|29000|490455.323546531|494449.909524532|3994.58597800107|https://bitcointalk.org/index.php?topic=641696.msg16092344#msg16092344|
|2017-11-05|20:43:08|464630.505929712|29000|493630.505929712|501658.091911715|8027.58598200331|https://www.reddit.com/r/Aeon/comments/7a8b2y/aeon_dev_funds/dpee983?utm_source=share&utm_medium=web2x&context=3|
|2021-02-15|01:22:16|445400.615362308|69000|514400.615362308|546679.871344312|32279.2559820036|https://github.com/aeonix/aeon/issues/215|

**Comment by ghost** [comment]
Here is csv I used. 
[my_txns.txt](https://github.com/aeonix/aeon/files/6066132/my_txns.txt)
Credit john cross https://monero.stackexchange.com/a/6072

**Comment by iamsmooth** [comment]
You're probably counting change, which is a known issue with view key wallets.

It's never been moved before this proof of funds process.

**Comment by ghost** [comment]
Ok I yeah I forgot about that.

**Comment by ghost** [comment]
Gladly, the majority has been accounted for. Still there is some discrepancy not explainable by change. Something between 2016-08-30 2017-11-05 appears missing possibly a bounty I have not discovered. It is too bad we do not have records for such change transactions, that may be wise to record going forward. 


Date | Time | Reported Donation Fund | Reported Spent | Reported Received | Actual Received | Estimated Change | Change added | Difference | Reference
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
2015-04-30 | 21:58:33 | 5494.56612723058 | 0 | 5494.56612723058 | 5494.56612723058 | 0 | 0 | 0 | https://bitcointalk.org/index.php?topic=641696.msg11244951#msg11244951
2015-07-22 | 12:51:34 | 413537.378217015 | 19000 | 432537.378217015 | 435063.506989389 | 2526.12877237401 | 2526.12877237401 | 0 | https://bitcointalk.org/index.php?topic=641696.msg11945548#msg11945548
2015-09-06 | 10:48:33 | 439488.953356883 | 19000 | 458488.953356883 | 461679.330547446 | 2526.12877237401 | 0 | 664.248418188945 | https://bitcointalk.org/index.php?topic=641696.msg12346873#msg12346873
2015-12-30 | 23:22:13 | 450158.232169666 | 29000 | 479158.232169666 | 483231.460765723 | 3408.9801778681 | 882.85140549409 | 664.248418188945 | https://bitcointalk.org/index.php?topic=641696.msg13396158#msg13396158
2016-08-30 | 11:39:13 | 461455.323546531 | 29000 | 490455.323546531 | 494449.909524532 | 3408.9801778681 | 0 | 585.605800132849 | https://bitcointalk.org/index.php?topic=641696.msg16092344#msg16092344
2017-11-05 | 20:43:08 | 464630.505929712 | 29000 | 493630.505929712 | 501658.091911715 | 3408.9801778681 | 0 | 4618.60580413492 | https://www.reddit.com/r/Aeon/comments/7a8b2y/aeon_dev_funds/dpee983?utm_source=share&utm_medium=web2x&context=3
2021-02-15 | 01:22:16 | 445400.615362308 | 69000 | 514400.615362308 | 546679.871344312 | 27660.6501778691 | 24251.670000001 | 4618.60580413492 | #215
2021-03-01 | 17:06:10 | 445369 | 69000 | 514369 | 1908182.56434431 | 1389194.95854018 | 1361534.30836231 | 4618.60580413486 | #215

**Comment by ghost** [comment]
Smooth, can you agree there is total 69000 spent from dev fund? Or maybe you can provide output for `aeon-wallet-cli --command "show_transfers" --wallet-file=/path/to/wallet --password 'password' | egrep '^ '| sed 's/^ //g'| sed 's/ \+/,/g' >> my_txns.csv` I can dig through it.

**Comment by iamsmooth** [comment]
I don't have an accounting of spending other than what was reported in a fragmented manner on the bitcointalk thread, maybe on reddit, etc. As a result I can't make any statements about how much was spent. I can say that there wasn't any other spending besides what was reported. It is a good implied point that a better job of keeping track of it should have been done.

I can provide the show_transfers.

**Comment by ghost** [comment]
That would be helpful. Perhaps I can piece together some meaningful record, try to identify change inputs and move forward with more transparency in the future. Some level of trust is here no matter what, haha but at least we can have some record. and the funds are proven now so at least that can no longer be in doubt.

**Comment by iamsmooth** [comment]
Is there something of appropriate size paid out right around the time of the BTC donation (see BTC address above)? I vaguely recall that might have been a trade in exchange for some fo the donated AEON with a community member, but I don't recall the details.

**Comment by iamsmooth** [comment]
Oh wait, you can't tell that without the show_transfers. I'll get that uploaded soon.

**Comment by ghost** [comment]
That seems to match the right timeframe but yeah without transfers it is hard to say. I am attempting to document all the actions thus far related to dev funds bounties etc.  If it is not too much for you because it would really boost the credibility of the report.

**Comment by iamsmooth** [comment]
Uploaded the log here https://github.com/iamsmooth/aeon-donations-audit/blob/main/aeon-donations-transfers.csv

I removed the large number of transfers at the very end when I was consolidating the wallet. If that somehow turns out to be relevant I can upload those as well

**Comment by ghost** [comment]
Ok, everything has been verified. I wrote the donation fund review here https://docs.google.com/document/d/1X5Ansi0B9ruAaLHoP7v4Xu8vi79AHnLRztDKyvXRzhk/edit?usp=sharing . Possibly this can be added to the website or some other public location. 

In summary, totally 517,501.2054 AEON and 0.81 BTC have been received, 72,132.2054 AEON have been spent, and, as of 03-04-2021, there remains 445,369 AEON and 0.81 BTC in the donation fund.

Thank you to everyone for helping with this review.

**Comment by BigslimVdub** [comment]
> Ok, everything has been verified. I wrote the donation fund review here https://docs.google.com/document/d/1X5Ansi0B9ruAaLHoP7v4Xu8vi79AHnLRztDKyvXRzhk/edit?usp=sharing . Possibly this can be added to the website or some other public location.
> 
> In summary, totally 517,501.2054 AEON and 0.81 BTC have been received, 72,132.2054 AEON have been spent, and, as of 03-04-2021, there remains 445,369 AEON and 0.81 BTC in the donation fund.
> 
> Thank you to everyone for helping with this review.

Feel free to add the information to the community repo here as well  https://github.com/AEONCommunity/DevFundReview

**Comment by ghost** [comment]
Thanks for the recognition, Dev Slim. Is there any more public location like a twitter account? I feel it will not help to put it in a small repo as it may be even more lost.

**Comment by BigslimVdub** [comment]
> Thanks for the recognition, Dev Slim. Is there any more public location like a twitter account? I feel it will not help to put it in a small repo as it may be even more lost.

https://twitter.com/aeoncommunity/status/1367690254199762944?s=21

**Comment by ghost** [comment]
Sweet, hopefully a search engine can pick up on that.
