### ISSUE TITLE
donate the dev fund of a forked blockchain to the fork

### ISSUE THREAD

**Issue by ghost** [aeonix/aeon#216]
It seams some one wants to fork aeon....
I'm proposing, to donate to them the whole dev fund of the forked blockchain (not the one of the aeon chain... lol)

aeon hodlers become hodlers in the fork too, so we should sincerely wish them good luck.

**Comment by iamsmooth** [comment]
It's debatable whether we should do that or just consider it as part of a larger AEON dev fund (and one that can be sold to pay for things without hurting the price of AEON). I wouldn't rule it out, the above argument you made has some validity.

**Comment by BigslimVdub** [comment]
Huh? 

A turtlecoin dev was attempting to do this in 2017 branding it Aeon classic and the coin they forked (from turtlecoin base not aeon) ended up dying. I see no reason to purposely fork Aeon to gather high amounts of forked coins for a sole entity. This would most likely not be helpful to the project at all and appear as money grab for anyone doing so. 

If someone wanted to fork Aeon they could have done it at the last two hard forks. It does not appear anyone did so. With so much interest in not using k12 it is surprising that nobody did try to fork Aeon yet.
