### ISSUE TITLE
Bigshot mods on /r/aeon blocked my account. Do we need them?

### ISSUE THREAD

**Issue by mother-trucker-530** [aeonix/aeon#217]
Look at the votes. My posts are attracting many users. There is difference from SPAM and free expression. But clearly free expression is not permitted in this group. Mods say they are not cool enough for them. So what does it take to get their holy blessing? They have abandoned the subreddit for years only to come back delete my posts and criticize me.

**Comment by iamsmooth** [comment]
Off topic for this repo
