### ISSUE TITLE
Please help with 0 balance

### ISSUE THREAD

**Issue by livingsb** [aeonix/aeon#218]
I created an Aeon GUI wallet. Running the node. I deposited some Aeon yesterday. Was in there safe and sound. I looked this morning 0.0000 balance.I am a bit of a crypto newb, but what would cause this? I have a Monero GUI wallet which is similar, but I have never seen anything like this. There is no history of my transaction. I only have one wallet. Any suggestion?

I am 10000% positive that the coins were int there last night. The wallet is synched. I tried a remote node - still no history or balance. I was running a Monero node at the same time. I shut that down.

The history is there from Trade Ogre.

Thanks for your help.

**Comment by ghost** [comment]
Did you solve this?

**Comment by livingsb** [comment]
I did! Thanks for responding.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by setuidroot** [comment]
@livingsb Can you post some screenshots?  It could be your node is out of sync with the Aeon network.

**Comment by livingsb** [comment]
Thanks for the response. I opened the wallet on another computer and teh balance was intact. I believe you are corre3ct about the node being out of sync.

Thanks again!

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by BigslimVdub** [comment]
If this is resolved, please close

**Comment by livingsb** [comment]
Resolved thanks!

**Comment by ghost** [comment]
Hello, livingsb

We cannot close the github issue for you so please come to visit the github page for Aeon and close the issue since you have had it resolved. At the bottom of the issue page you will see a red button for closing the issue. 

Thanks.

**Comment by livingsb** [comment]
is it closed? won't let me click on the red button

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ghost** [comment]
Yes, it was closed by "aeonix" a few hours ago.  Thanks for checking.
