### ISSUE TITLE
idea for an ASIC miner with extremly low electricity consumption

### ISSUE THREAD

**Issue by ghost** [aeonix/aeon#223]
EDIT: This is not an advice for miners. It's a strategy for the project. This is a general idea to build asic miners that consume almost no energy.

How to build a cryptocurrency miner, with very low power consumption?

In short, you reduce the frequency of the equipment, as low as it can possibly go, say 1kHz-100Hz-10Hz. The lower the frequency, the lower the energy consumption, per hash (not linear). You compensate, with more hardware. Because the energy consumption is so low, you can cram a considerable amount in a small space. Something like an SSD. For this to work well, an adequate hashing algorithm is needed. Maybe been fast is enough. This is inspired from the biological brain.

Proof of work, actually cares about how much money you spent, not how much energy you wasted. If you make the mining equipment expensive, you waste less energy. And with the above, the expense, is the manufacturing process, not some monopoly. I think the economics work out. The human brain does something similar and it consumes 20W in 2litres( ~100Hz), a normal computer simulating a human brain would consume 1GW in a house (~1Ghz). The difference in cost for mining, would probably be in the same order of magnitude.

What you think guys? What's the obvious error i'm missing?

**Comment by tomato5040** [comment]
What is the frequency measuring?

**Comment by ghost** [comment]
@iamsmooth

i want to discuss a strategy for the project
a different approch to mining
say something
