### ISSUE TITLE
Build failure due to apple silicon

### ISSUE THREAD

**Issue by BigslimVdub** [aeonix/aeon#236]
[CMakeLists.txt](https://github.com/aeonix/aeon/files/6819797/CMakeLists.txt)

https://github.com/monero-project/monero/pull/7736
https://github.com/monero-project/monero/pull/7689
https://github.com/monero-project/monero/pull/7435
https://github.com/monero-project/monero/pull/7074

Build failing on M1 device.
Linking CmakeLists.txt changes as well as boost 1.76.0 requirements.

**Comment by BigslimVdub** [comment]
Successful build on M1 with osx 11.4 making the above changes on current master.

**Comment by ghost** [comment]
Understood, I will submit a separate PR for you on this topic.

**Comment by ghost** [comment]
@BigslimVdub , do you have a test machine?

**Comment by ghost** [comment]
Started^^ please test when you can.

**Comment by ghost** [comment]
I guess resolved, eh? :+1:
