### ISSUE TITLE
Seed nodes down?

### ISSUE THREAD

**Issue by ghost** [aeonix/aeon#237]
Can't find any peers. Anyone else seeing problems like this? #235 could help with this but possibly some additional nodes could be good to add as well.

**Comment by stoffu** [comment]
According to the log, those two seed nodes were added by @iamsmooth (https://github.com/aeonix/aeon-legacy/pull/9, https://github.com/aeonix/aeon-legacy/pull/24), so he should know what happened to them.

New seed nodes by other volunteers would certainly be very welcome.

**Comment by BigslimVdub** [comment]
```Height: 1385164/1385164 (100.0%) on mainnet, not mining, net hash 8.99 TH/s, v9, 6(out)+13(in) connections```

My node is not having any issues currently.

**Comment by ghost** [comment]
What is the IP, @BigslimVdub ? I launched some additional nodes. Are there special requirements for them to operate as seed node, does anyone know?

**Comment by stoffu** [comment]
@yorha-0x 
> I launched some additional nodes. Are there special requirements for them to operate as seed node, does anyone know?

No special requirements, as long as the node has its port open so that others can connect.
Just add your IP to the hard-coded seed node list, see https://github.com/aeonix/aeon/pull/235

**Comment by iamsmooth** [comment]
I need to look into what happened to the nodes. I'm not sure. I'll have more time to research in a few weeks. Meanwhile, there is a PR for adding stuffu's seed, which I will merge.

**Comment by iamsmooth** [comment]
Also can let users know that if they are trying to connect before there is a new release, --add-seed-node (CLI) can be used with any of the new seed nodes. Not sure how that is done with GUI.

**Comment by ghost** [comment]
Thanks. Hoping we can get a release out because I think users will be confused by this if the daemon does not automatically start correctly.

**Comment by iamsmooth** [comment]
I'll look right now to see if I can get at least one of them back up.
