### ISSUE TITLE
Please review open PRs

### ISSUE THREAD

**Issue by iamsmooth** [aeonix/aeon#239]
I would like to resume merging them but some are old and I'm not sure if any have conflicts. Please review all open PRs and advise if any need to be updated or closed without merge. Thanks.

**Comment by stoffu** [comment]
I have reviewed and approved some PRs from @yorha-0x.
Those approved PRs have no conflicts.

I cannot review my own PRs.

I'd advise to merge #228 which makes all the CI tests pass first so that other PRs can rebase against the new master and confirm there is no error in the CI.

**Comment by iamsmooth** [comment]
Thank you for the info and suggestion. I'll merge #228 shortly.

**Comment by ghost** [comment]
Reviewed.

**Comment by ghost** [comment]
#225 also has a CI fix. See #231

**Comment by ghost** [comment]
Oh nevermind^.

**Comment by iamsmooth** [comment]
I think we're almost there. Any particular issues to note with the open PRs? I'm skipping #226 due to the request in the PR not to merge it.

**Comment by iamsmooth** [comment]
All merged now except #226 which is held as requested there.

Closing this, as there is no remaining backlog of open PRs.
