### ISSUE TITLE
Release minor version 0.14.1.1 for new seed nodes

### ISSUE THREAD

**Issue by ghost** [aeonix/aeon#241]
Does anyone support this? Also what needs to be done for a new release and can I help with that?

Old seed nodes are still down `./aeond --add-exclusive-node=74.91.23.186:11180 --add-exclusive-node=192.187.114.114:11180`

**Comment by iamsmooth** [comment]
I'm in favor of a new release, though I'm not sure whether we need a triple dot release just for this or can roll some of the more substantial changes into one.

**Comment by stoffu** [comment]
@iamsmooth What was the outcome of your investigation into those seed nodes?

https://github.com/aeonix/aeon/issues/237#issuecomment-933038963

> I need to look into what happened to the nodes. I'm not sure. I'll have more time to research in a few weeks. Meanwhile, there is a PR for adding stuffu's seed, which I will merge.

**Comment by iamsmooth** [comment]
@stoffu Wasn't able to investigate yet. Looking at it right now.

**Comment by iamsmooth** [comment]
> 192.187.114.114

This one is not mine, or if it once was, it isn't any more. It likely needs to be removed. I'm still investigating the other one.

**Comment by iamsmooth** [comment]
The 74.91.23.186 seed node is back up.

**Comment by ghost** [comment]
Ok, good. In that case a new version is not very urgent.
