### ISSUE TITLE
Direct fetching of external/miniupnp failed

### ISSUE THREAD

**Issue by boulder0o** [aeonix/aeon#260]
.

**Comment by BigslimVdub** [comment]
git submodule init && git submodule update before building

**Comment by boulder0o** [comment]
Wrong. Go get yourself a copy of current LTS Ubuntu 20 

git submodule init && git submodule update
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 59 (delta 38), reused 45 (delta 28), pack-reused 0
Unpacking objects: 100% (59/59), 16.82 KiB | 382.00 KiB/s, done.
From https://github.com/miniupnp/miniupnp
 * [new branch]      cmake-pkg-config -> origin/cmake-pkg-config
   1f46c25..9df2f43  master           -> origin/master
 * [new tag]         miniupnpd_2_3_0  -> miniupnpd_2_3_0
fatal: remote error: upload-pack: not our ref 4c700e09526a7d546394e85628c57e9490feefa0
fatal: the remote end hung up unexpectedly
Fetched in submodule path '../external/miniupnp', but it did not contain 4c700e09526a7d546394e85628c57e9490feefa0. Direct fetching of that commit failed.

**Comment by boulder0o** [comment]
Kicked from the Discord for pointing this out. Lame coin.

**Comment by boulder0o** [comment]
Coin is sabotaged .

**Comment by boulder0o** [comment]
Big Slim thinks I was using a Mac M1 LMAO! that was the reasoning given!!!!! HAHAHAH

**Comment by boulder0o** [comment]
its just ppl's money, NBD

**Comment by boulder0o** [comment]
they're just waiting for someone to invest $10k and rip them . switched to FPGA ASIC mining despite swearing never to do it. the biggest joke of a coin in "crypto land" as Big Slim refers to it.

**Comment by boulder0o** [comment]
if you put more than $20 on this coin, ur stupid at monumental levels and will pay Big Slim's motorcycle

**Comment by boulder0o** [comment]
I invest 50 cents in this coin, got all the info I need to know.........................do your DD . dont listen to "admins"

**Comment by boulder0o** [comment]
I reported this repository to Github for abuse.

**Comment by boulder0o** [comment]
Ubuntu 20 is the current LTS version. This project's build instructions rely on Ubuntu 16/18, which is legacy at this point. Repo maintainer is asleep at the wheel...

**Comment by iamsmooth** [comment]
LTS = long term support

Meaning that rapidly upgrading to the latest and greatest is not required. Continuing to support the older versions is fine.

I do agree the instructions should be updated for 20.04, if only to note that they still work (if they do).

16.04, unlike 18.04. has reached end of life and could be dropped (but still on extended support I think, so some may still use it).

**Comment by iamsmooth** [comment]
Also, kindly refrain from market commentary on GitHub. This is for development issues.

**Comment by boulder0o** [comment]
I cannot take you seriously, smoothxmr. We call you the psychedelic sunglasses man in my neck of the woods. This project badly needs some fresh developers that aren't afraid of the latest and greatest.

**Comment by boulder0o** [comment]
You think I don't know why LTS means? You got until April 2023... max. Time is ticking. I always had trouble coding with sunglasses on...
