### ISSUE TITLE
fix coinmarketcap wrong supply figure, team member required

### ISSUE THREAD

**Issue by ghost** [aeonix/aeon#276]
coinmarketcap can be contacted now. I submitted a ticket for the block explorer that they fixed. But they are a dense vogon bureaucracy and they insist for a team member, with an **official email address** to contact them. You also need to show to them the email address on the official project site.

```
For supply updates, kindly get a team member to submit a request via the following form.
 
4 - [Existing Cryptoasset] Update supply figures - https://support.coinmarketcap.com/hc/en-us/requests/new?ticket_form_id=360000493092
```

Yes, they replaced the block explorer that also mentions supply, but they will not change their script that probably scrapes the old block explorer with the new one unless a team member does the asking.

**Comment by BigslimVdub** [comment]
I have tried for years and never got any responses back from them so good for you being able to actually get ahold of them for the block explorer issue. 

@iamsmooth how have you been in contact with Bittrex for “formal” communications since github doesn’t allow for email handling on their websites to add a domain to an email?

In all actuality, one could spoof an email with the @aeon.cash if they wanted to but that isn’t the correct way to do this.

**Comment by ghost** [comment]
I don't know how he did with bittrex, but you can have a public email address on your github profile. They could accept that.

**Comment by iamsmooth** [comment]
Bittrex is an outlier. I already was in contact them for years, before they had any sort of process.

I'd suggest appointing yourself as a team member for  community development or some such ill-defined title and PR-ing it onto some obscure part of the web site.

**Comment by ghost** [comment]
You can't basically give an official email address to some commentard you just found on the internet. A bit of common sense....

**Comment by iamsmooth** [comment]
There are no "official" addresses, that's the point you are missing. It's a community run project. If some third party wants your email address on the web site, put it there. Team members are anyone who puts in effort. If people are helpful they're welcome and if disruptive they'll be rejected by the rest of the community.

**Comment by ghost** [comment]
@iamsmooth 
~~In the aeonix account, set a public email address. "com dot protonmail at aeoncoin"~~
(exactly like that, if it lets you)
Give me a way to also share the password in secret.

for the website.... probably it should go in the presskit section.

**Comment by ghost** [comment]
@aeonix 
Who ever controls this account. add "com dot protonmail at aeoncoin" as the public email for the aeonix account. Also give me a secure way to share with you the credentials of the email account. Read the above messages for context.
