### ISSUE TITLE
[idea] specialized compression for the block chain

### ISSUE THREAD

**Issue by ghost** [aeonix/aeon#279]
If you use a specialized compression algorithm, you can achieve greater compression ratios. You know the structure of what you are compressing, and can take better advantage of the redundancies.

for example, wallet addresses are long and repeat a lot. You could make a table and re-encode them with something smaller.  You know, that a lot of blocks are empty. You know the reward algorithm. Do you really need the hashes of the blocks? Maybe you can just keep the nonce? You can cherry pick the algorithms to compress various bits and peaces.

You could also use "key frame" blocks, so that you don't have to parse the whole thing from the beginning each time.

**Comment by stoffu** [comment]
Your argument is a total nonsense to me. I suggest closing this issue.

**Comment by iamsmooth** [comment]
@pirate486743186 Addresses don't repeat on a cryptonote style blockchain. Each time an address is used, a one-time output key is created. 

That's probably the main thing that might repeat (but doesn't) so there really isn't much room for compression.

So, yes, I agree with @stoffu this should be closed.
