### ISSUE TITLE
Can't compile latest version 0.12.1.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by shigutso** [aeonix/aeon#34]
Compiling following the instructions (git clone with --recursive):
https://pastebin.mozilla.org/9087811

Compiling by downloading the source code on the release page:
https://pastebin.mozilla.org/9087812

What I get after getting errors crashing me out:

```
ubuntu@ubuntu:~/aeon/build/release/bin$ ls -lh
total 13M
-rwxrwxr-x 1 ubuntu ubuntu 4.1M Jun 17 12:25 aeon-blockchain-export
-rwxrwxr-x 1 ubuntu ubuntu 4.3M Jun 17 12:25 aeon-blockchain-import
-rwxrwxr-x 1 ubuntu ubuntu 4.1M Jun 17 12:25 aeon-blockchain-usage
ubuntu@ubuntu:~/aeon/build/release/bin$

```
My Ubuntu version (x86_64):

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```
It's a 8 thread CPU with 16GB of RAM.

What am I doing wrong? Could compile version 0.12.0 without any issues, following the same instructions.

**Comment by shigutso** [comment]
Successfully compiled on Ubuntu 18.04... dependency problems then?

**Comment by stoffu** [comment]
For the former, the error is:
```
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
tests/net_load_tests/CMakeFiles/net_load_tests_clt.dir/build.make:130: recipe for target 'tests/net_load_tests/net_load_tests_clt' failed
```
which means that the distributed libgtest.a wasn't built with the required -fPIC flag. You can avoid this by simply uninstalling it: `sudo apt remove libgtest-dev`. Ubuntu 18 works because (most of) the distributed packages are built with -fPIC.

For the latter, the error is:
```
CMake Error at external/CMakeLists.txt:42 (add_subdirectory):
  add_subdirectory given source "miniupnp/miniupnpc" which is not an existing
  directory.
```
which is because the source tarball doesn't contain any git submodules. Basically the tarball is unusable, you need to use git in order to get the submodules properly initialized.

**Comment by shigutso** [comment]
I did the `sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libg* /usr/lib/` as instructed, I thought that solved that problem? Was something changed that prevents 0.12.1 from compiling on older versions? Because 0.12.0 compiled without any issues on the same machine.

Can I compile it without `libgtest-dev`?

Thanks

**Comment by stoffu** [comment]
Nothing changed in 0.12.1 regarding gtest. Probably you weren't building it by having the `BUILD_TESTS` flag to `OFF` unknowingly.

GTest is included in the repository and gets compiled if the system installed one isn't found. And it's not needed for building actual applications (aeond, aeon-wallet-cli, etc) anyway; it's only needed for building tests.

**Comment by bobbieltd** [comment]
Try this : 
1. cd /usr/src/gtest
2. sudo nano CMakeCache.txt
Look for this and add -fPIC in content : 
//Flags used by the compiler during all build types.
CMAKE_CXX_FLAGS:STRING=-fPIC
3. sudo make && sudo mv libg* /usr/lib/

Then recompile Aeon

**Comment by shigutso** [comment]
That did the trick, thanks @bobbieltd 
Weird that with the exact same setup did compile version 0.12.0...
