### ISSUE TITLE
Wallet rpc problem

### ISSUE THREAD

**Issue by ArqTras** [aeonix/aeon#35]
1. Problem with payments using wallet-rpc 
ERROR   net.http        contrib/epee/include/net/jsonrpc_structs.h:21   Exception on unserializing: unexpected int value with signed storage value less than 0, and unsigned receiver value

ERROR   cn      src/cryptonote_basic/cryptonote_format_utils.cpp:190    Failed to parse transaction from blob
ERROR   wallet.wallet2  src/wallet/wallet2.cpp:5709     !cryptonote::parse_and_validate_tx_from_blob(bd, tx, tx_hash, tx_prefix_hash). THROW EXCEPTION: error::wallet_internal_error
WARN    net.http        src/wallet/wallet_errors.h:794  /home/pooldaemon/daemons/aeon/src/wallet/wallet2.cpp:5709:N5tools5error21wallet_internal_errorE: failed to parse tx from blob
Still exist even delete dir for saving data and full resync
ERROR   wallet.wallet2  src/wallet/wallet2.cpp:3890     Failed to save rings, will try again next time

**Comment by stoffu** [comment]
Did you use curl or some other automated methods? If the former is the case, please post the entirety of your terminal command logs. If latter, please provide more details. Also please provide the full log (aeon-wallet-rpc.log) with some info (e.g. wallet address) masked if desired.

**Comment by ArqTras** [comment]
Looks like my json rpc request failed and provide that error. Even that direct to Your email i send You log from rpc wallet
