### ISSUE TITLE
Remote daemon with custom port showing two ports in wallet-cli

### ISSUE THREAD

**Issue by camthegeek** [aeonix/aeon#44]
When using a custom port on --daemon-host, wallet shows -> Warning: using an untrusted daemon at http://host:11187:11181, privacy will be lessened

**Example command:** 
./aeon-wallet-cli --daemon-host host:11187

**Issue:** 
Error is showing two ports, one actual port to use, one is default port. 

https://github.com/aeonix/aeon/blob/master/src/simplewallet/simplewallet.cpp#L3147

m_wallet->get_daemon_address() returns http://host:custom_port:RPC_DEFAULT_PORT

**Comment by stoffu** [comment]
You're misusing the flags. The daemon address in the `<host>:<port>` format should be given to the `--daemon-address` option. When this option is unspecified, one can specify one or both of the `--daemon-host` and `--daemon-port` options, which get concatenated to form the full daemon address.

**Comment by camthegeek** [comment]
I'm aware of the --daemon-port flag and how to use it but was under the assumption that --daemon-address was able to do the same thing without needing the extra flag given the help file says  `Use daemon instance at <host>:<port>`

My thoughts are --daemon-port could be set based off splitting the arguments of --daemon-address after `:`

**Comment by stoffu** [comment]
If you can suggest a clearer help message, please send a PR to Monero.

**Comment by camthegeek** [comment]
My issue was using the aeon-wallet-cli that was packed with one of the earlier releases of aeon-gui.

Replacing that aeon-wallet-cli with a more up to date version resolves the issue.

FIX: Use updated software.
