### ISSUE TITLE
Build fails on 32-bit Manjaro

### ISSUE THREAD

**Issue by ordtrogen** [aeonix/aeon#52]
My machine:
Linux manjaro 4.9.124-1-MANJARO #1 SMP PREEMPT Fri Aug 24 17:22:16 UTC 2018 i686 GNU/Linux

(Manjaro is a prepackaged Arch Linux installation)

Looks like the problem PR'd here:

https://github.com/monero-project/monero/pull/4274

(I don't know if this should be fixed by an upstream merge or otherwise. Might be good to have it mentioned here)

**Comment by stoffu** [comment]
#53
