### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by izzyneko** [aeonix/aeon#57]
which is the version of aeon cryptonight-lite  Algorithm

**Comment by 420coupe** [comment]
Cryptonight-Lite v7

**Comment by izzyneko** [comment]
so 
does the baikan miner (cryptonight-lite) work for aeon mining ?

**Comment by 420coupe** [comment]
No, AEON is V7. Not cryptonight-lite, AEON forked off this in June as did Monero to fork off the ASICs
