### ISSUE TITLE
Name for the next release

### ISSUE THREAD

**Issue by stoffu** [aeonix/aeon#6]
We haven't decided yet what to call the new rebased version.

A while ago there was a thread on reddit discussing the possible ideas for naming conventions: https://www.reddit.com/r/Aeon/comments/8bcgyd/we_could_start_a_name_convention_for_aeon_releases

Two possible naming conventions were proposed:
- pick names of Greek deities (https://en.wikipedia.org/wiki/List_of_Greek_mythological_figures)
- pick names related to Gnosticism (https://en.wikipedia.org/wiki/Aeon_(Gnosticism))

Some users suggested particular names:
- Phoenix (the same as current)
- Freya
- Aphrodite
- Athena
- Dionysus

My pick is from Gnosticism word: **Sophia**

Unfortunately there's not much time left for this poll since we're targeting the hardfork date on May 28th.

Please speak up!

**Comment by BigslimVdub** [comment]
Cronos 0.10.0 - leader and youngest of the first generation of CN_L

**Comment by devopsralf** [comment]
Archon-Alethia , Aeon-Creator - and Truth combined

or 

Pleroma - to complete an incomplete thing

**Comment by dprestegard** [comment]
I love your idea, Stoffu!

Sophia sounds fitting to me.

**Comment by SomaticIllusions** [comment]
I vote for Sophia. Thank you for your hard work. :))

**Comment by gimbol** [comment]
Sophia is perfect. +1

**Comment by Vaidas737** [comment]
Sophia +1

**Comment by peanutsformonkeys** [comment]
I would go for the "whenrebaseyo" release. Aeon should be fun.

**Comment by frnrbrt** [comment]
Athena, the ancient goddess of wisdom. Sophia sound good too.

**Comment by shigutso** [comment]
0.12 GTFO ASICs Edition

after that we can name it greek stuff idc

**Comment by schwagdawg** [comment]
Sophia!

**Comment by campassi** [comment]
She will be named, Sophia.

**Comment by wyattp11** [comment]
Aren't we closer to this?

> Valentinus assumed, as the beginning of all things, the Primal Being or Bythos, **who after ages of silence and contemplation**, _gave rise to other beings by a process of emanation_.

Seems fitting for Aeon.

**Comment by LegolasGChief** [comment]
Arkenstone ;)
Aeon Arkenstone sounds nice, relates to mining :)

\+ my pool name will become super relevant xD

**Comment by metamirror** [comment]
Sophia is fine. I also like Galatea: https://en.wikipedia.org/wiki/Galatea_(mythology)

**Comment by stoffu** [comment]
Thank you all for your input, and I'm glad that my proposal "Sophia" received support from sufficiently many people. Let's conclude this poll and go with this release name.
