### ISSUE TITLE
Removing tail emission or starting it at..

### ISSUE THREAD

**Issue by abhishek1104** [aeonix/aeon#66]
To the best of my knowledge the static emission will be
1.20000000000 Aeon 

I propose to remove the tail emission or start it much lower ,with an emphasis on promoting the usability of those so long decimal places....

We are having up to 12 decimal places in each unit of Aeon and still the tail emission is set to start fixing it at 1.2 Aeon per 4 minute block.

Why not start at 0.120000000000 or at 0.012000000000 or much below it.....

Keeping into consideration of dynamic block size for which tail emission will play an important role...Why can't we have declining slowly towards 0 (promoting the use of those so long decimal places with assumption that in future they would be of something worth,not assuming that they would always be worthless FOREVER.)

**Comment by abhishek1104** [comment]
I appreciate your views.
Just to make it clear I am never ever in favour of starting a new chain of Aeon..

Just wanted to know the technical perspective of keeping it fixed at 0.3 Aeon / min not below that.

If I am not wrong then in Monero as well tail emission never got full agreement from the community in history as well.

**Comment by stoffu** [comment]
> If I am not wrong then in Monero as well tail emission never got full agreement from the community in history as well.

AFAIK there was no severe contentions about the concept of tail emission and the actual rate. If I’m wrong, could you provide some links?

Some coin parameters like emission rate have to be chosen arbitrarily (as long as reasonable); it’s difficult to say which specific value is optimal.

**Comment by abhishek1104** [comment]
That's fair enough.
What's your 2nd paragraph says is what I am saying exactly....

Anyways very interesting threads (not to prove anyone wrong or right -- dynamic Blockchain logic holds it against virtually everything)
https://bitcointalk.org/index.php?topic=753252.msg12440450#msg12440450




I am just for proposing a critical healthy discussion related to reconsider the fixed rate of tail emission in Aeon.If community along with core devs and other intellects agree.(Even if the value differs from Monero)

Same points as following

https://www.reddit.com/r/Monero/comments/8goy71/tail_emission_critical_discussion_why_notwhywhy/

**Comment by stoffu** [comment]
To me, the need for the tail emission seemed as obvious as the need for the PoW for consensus mechanism (instead of others like PoS). If one was opposed to it, she wouldn't join the protocol in the first place. As such, I'm a bit hesitant to call this discussion "critical and healthy", although expressing opinions never hurts.

**Comment by stoffu** [comment]
Decimal place has no role here; it’s only for the sake of visual perception. All amounts are internally represented as integers, e.g. 0.3 Aeon is internally 3*10^11. What you proposed here is to reduce that number to whatever, which I’m strongly against. Do you still intend to push your proposal?

**Comment by abhishek1104** [comment]
Well I rest my case here.

Though personally I agree with all the points apart from 3*(10 pow 11) value fixation logic nothing more or less than that.

As per proposal it's all on community,Dev's etc to decide on the same.Still there is long time for tail emission to start and not so critical at this point of time,in future if it is considered then would be great ,if not then also fine.

Also hope you start working on BP implementation soon and keep doing great work for Aeon...

**Comment by BigslimVdub** [comment]
I believe the current tail emission will work as needed so long as the network sees normal usage and transactions in blocks.

**Comment by stoffu** [comment]
> apart from 3*(10 pow 11) value fixation logic nothing more or less than that.

So you don’t seem to be agreed with the idea of tail emission in the end. Maybe then Wownero is better fit for you which doesn’t have tail emission; it’s also a fairly launched coin.
