### ISSUE TITLE
wallet files seem to not work on nfs mounted directories

### ISSUE THREAD

**Issue by ghost** [aeonix/aeon#85]
aeon version 0.12.8.0:

Error: failed to load wallet: internal error: "???.keys" is opened by another wallet program.

If the wallet is copied to a local directory, there's no error. If the wallet is copied back to nfs, with a different name, the error occurs again.

**Comment by stoffu** [comment]
Could you please try to reproduce the same with Monero, and if reproduced, open an issue in Monero's bug tracker?

**Comment by BigslimVdub** [comment]
are you trying to open a wallet two times at the same time but listed in different directories? Your wallet.keys file may become corrupted if copying and changing names, I have seen this on osx and windows before. Simply copy and paste I have not seen the issue.

**Comment by ghost** [comment]
Reproducable for monero: https://github.com/monero-project/monero/issues/4942

I'm pretty sure no other program is trying to open the file, maybe it's just my NFS setup...

**Comment by shigutso** [comment]
@stoffu https://github.com/monero-project/monero/pull/4944 seems to fix the issue, could you push this one to aeon?

**Comment by stoffu** [comment]
@shigutso Thanks for the hint, #97
