### ISSUE TITLE
Unable to copy/paste an address (e.g., exchange deposit address) to the simplewallet command for transfer

### ISSUE THREAD

**Issue by L7788** [aeonix/aeon#97]
Is there any way can copy/paste an address (e.g., exchange deposit address) to the simplewallet command  for transfer, other than manually type each letter?

**Comment by stoffu** [comment]
Of course you should be able to copy/paste addresses; it'd have been a disaster if they needed to be typed manually! Do you have problems with copying/pasting?

**Comment by iamsmooth** [comment]
I think in Windows terminal you have to explicitly enable clipboard operations or something. I rarely use Windows so I'm not sure.

**Comment by L7788** [comment]
Please advise how to copy/paste under windows environment Aeon wallet.

**Comment by stoffu** [comment]
@L7788 I think it's a general matter of how to use the Command Prompt on Windows. You should be able to paste from clipboard by clicking on the window title bar with the right mouse button which opens up a context menu.

**Comment by L7788** [comment]
If figured that out already. Thanks

**Comment by cryptotym** [comment]
For anyone else, Right click the top bar of the program > Properties > Enable  "QuickEdit Mode" on the Options tab
