### ISSUE TITLE
QUESTION Does AEON support subaddresses like XMR?

### ISSUE THREAD

**Issue by normoes** [aeonix/aeon#98]
Is this feature going to be implemented at some point?

I am asking because of the Monero hard fork in October 2019 which is going to deprecate/remove the support for paymentIDs and integrated addresses.

Thank you.

**Comment by camthegeek** [comment]
Yes.

They begin with `Xn` as seen in the config here: https://github.com/aeonix/aeon/blob/master/src/cryptonote_config.h#L160

**Comment by normoes** [comment]
That's very nice :)
Thank you.
